CREATE TABLE EMPLOYEE (
  empId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  dept TEXT NOT NULL
);

INSERT INTO EMPLOYEE VALUES (0001, 'Clark', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0002, 'Dave', 'Contabilidade');
INSERT INTO EMPLOYEE VALUES (0003, 'Ava', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0004, 'Joe', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0005, 'Joe', 'Marketing');
INSERT INTO EMPLOYEE VALUES (0006, 'Sarah', 'HR');
INSERT INTO EMPLOYEE VALUES (0007, 'Joe', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0008, 'Ava', 'Finanças');
INSERT INTO EMPLOYEE VALUES (0009, 'Joe', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0010, 'John', 'IT');
INSERT INTO EMPLOYEE VALUES (0011, 'Joe', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0012, 'Lucas', 'Marketing');
INSERT INTO EMPLOYEE VALUES (0013, 'Emily', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0014, 'Joe', 'HR');
INSERT INTO EMPLOYEE VALUES (0015, 'Sophia', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0016, 'Daniel', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0017, 'Joe', 'Contabilidade');
INSERT INTO EMPLOYEE VALUES (0018, 'Olivia', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0019, 'Ethan', 'Engenharia');
INSERT INTO EMPLOYEE VALUES (0020, 'Mia', 'HR');
INSERT INTO EMPLOYEE VALUES (0021, 'Joe', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0022, 'Aiden', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0023, 'Chloe', 'IT');
INSERT INTO EMPLOYEE VALUES (0024, 'Liam', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0025, 'Joe', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0026, 'Benjamin', 'Marketing');
INSERT INTO EMPLOYEE VALUES (0027, 'Charlotte', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0028, 'Elijah', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0029, 'Amelia', 'Finanças');
INSERT INTO EMPLOYEE VALUES (0030, 'James', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0031, 'Zoe', 'Engenharia');
INSERT INTO EMPLOYEE VALUES (0032, 'Jack', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0033, 'Harper', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0034, 'Jackson', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0035, 'Isabella', 'HR');
INSERT INTO EMPLOYEE VALUES (0036, 'Gabriel', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0037, 'Ava', 'Contabilidade');
INSERT INTO EMPLOYEE VALUES (0038, 'Mason', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0039, 'Ella', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0040, 'Sebastian', 'IT');
INSERT INTO EMPLOYEE VALUES (0041, 'Lily', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0042, 'William', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0043, 'Grace', 'HR');
INSERT INTO EMPLOYEE VALUES (0044, 'Mila', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0045, 'Oliver', 'Engenharia');
INSERT INTO EMPLOYEE VALUES (0046, 'Nathan', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0047, 'Madison', 'Contabilidade');
INSERT INTO EMPLOYEE VALUES (0048, 'Ella', 'Marketing');
INSERT INTO EMPLOYEE VALUES (0049, 'Jameson', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0050, 'Layla', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0051, 'Henry', 'Vendas');
INSERT INTO EMPLOYEE VALUES (0052, 'Natalie', 'Vendas');


-- PARABENS, AGORA O PROXIMO VOCE VAI PRECISAR DE CODAR UM POUCO
-- CRIE UM CODIGO QUE:
--